apiVersion: v1
kind: Service
metadata:
  name: your-service-name
spec:
  selector:
    app: my-app  # Замените на подходящее значение, чтобы выбрать поды вашего контейнера
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
